/***************************************************************************
*                                       MICA
* File: stackBle.c
* Workspace: IMU_v4.0
* Project Name: 01_IMU_Stack_v4.0
* Version: v4.0.0
* Author: Craig Cheney
* 
* PCB: MICA_IMU_v3.5.2
* PSoC: CYBLE-214015-01 (EZBLE, 4.2, 256k)
* Sensors: BOSCH IMU (BMX055)
*
* Brief:
*   BLE software for the Stack program
* 
* 2017.07.31 CC - Document Created
* 2018.03.02 CC - Changed name to stackBle from micaOta
********************************************************************************/
#include "stackBle.h"

/* Private functions */
static CYBLE_API_RESULT_T startAdvertising(void);

/*******************************************************************************
* Function Name: initializeBLE()
********************************************************************************
*
* Summary:
*   Starts the BLE component and print debugging information 
*
* Parameters:
*   bleCallback - Pointer to function callback
*
* Return:
*   None
*
*******************************************************************************/
void initializeBLE(CYBLE_CALLBACK_T bleCallback){
    /* Declare private variables */
    CYBLE_API_RESULT_T apiResult;
    CYBLE_STACK_LIB_VERSION_T stackVersion;
    /* Start the application */
    apiResult = CyBle_Start(bleCallback);
    /* Ensure BLE started correctly */
    if(apiResult == CYBLE_ERROR_OK){
        /* Check if the stack version is correct */
        apiResult = CyBle_GetStackLibraryVersion(&stackVersion);
        if( apiResult == CYBLE_ERROR_OK) {
            DBG_PRINT("> Stack Version: ");
            DBG_PRINT_DEC_TEXT(stackVersion.majorVersion, ".");
            DBG_PRINT_DEC_TEXT(stackVersion.minorVersion, ".");
            DBG_PRINT_DEC_TEXT(stackVersion.patch,        ".");
            DBG_PRINT_DEC_TEXT(stackVersion.buildNumber, " Used Heap: ");
            DBG_PRINT_DEC_TEXT(CYBLE_STACK_RAM_SIZE, "\r\n");
        }
        else{
            DBG_PRINT("> CyBle_GetStackLibraryVersion API Error: ");
            DBG_PRINT_DEC_TEXT(apiResult, "\r\n");
        }
    }
    /* BLE component requires more heap to execute */
    else if( apiResult == CYBLE_ERROR_MEMORY_ALLOCATION_FAILED){
        DBG_PRINT("\r\nMEMORY_ALLOCATION_FAILED: need additional heap");
    }
    /* An error occured */
    else{
        DBG_PRINT("\r\nCyBle_Start API Error Occurred: ");
        DBG_PRINT_DEC(apiResult);
    }
}


/*******************************************************************************
* Function Name: bleOtaCallback()
********************************************************************************
*
* Summary:
*   Primary app call back for BLE. Processes the BLE stack events and acts
*   accordingly. 
*
* Parameters:
*   event - Event code generated by the stack
*   eventParam - pointer to the event parameters
*
* Return:
*   None
*
*******************************************************************************/
void bleOtaCallback(uint32 event, void* eventParam){
    /* Declare function scoped private variables */
    //CYBLE_API_RESULT_T apiResult;
    /* Act according to event */
    switch(event){
        /**********************************************************
        *                       General Events
        ***********************************************************/
        /* Stack initialized; ready for advertisement */
        case CYBLE_EVT_STACK_ON:{
            DBG_PRINT("> Stack ON\r\n");
            /* Start advertising */
            startAdvertising();
            break;
        }
        /**********************************************************
        *                       GAP Events
        ***********************************************************/
        /* Device need to display passkey during secure connection pairing */
        case CYBLE_EVT_GAP_NUMERIC_COMPARISON_REQUEST:{
            DBG_PRINT("> CYBLE_EVT_GAP_NUMERIC_COMPARISON_REQUEST\r\n");
            /* Send the passkey for authentication */
            CyBle_GapAuthPassKeyReply(cyBle_connHandle.attId, PASSKEY_IGNORE, CYBLE_GAP_ACCEPT_PASSKEY_REQ);
            break;
        }
        /* Device has been connected */
        case CYBLE_EVT_GAP_DEVICE_CONNECTED:{
            DBG_PRINT("> CYBLE_EVT_GAP_DEVICE_CONNECTED\r\n");
            /* Declare private variables */
            CYBLE_GAP_CONN_UPDATE_PARAM_T connUpdateParam;
            CYBLE_GAP_CONN_PARAM_UPDATED_IN_CONTROLLER_T connParam;
            /* Cast event params */
            connParam = *(CYBLE_GAP_CONN_PARAM_UPDATED_IN_CONTROLLER_T*) eventParam;
            /* Ensure connection parameters are valid */
            if( connParam.connIntv > CYBLE_GAPP_CONNECTION_INTERVAL_MAX ){
                /* Configure requested params */
                connUpdateParam.connIntvMin = CYBLE_GAPP_CONNECTION_INTERVAL_MIN;
                connUpdateParam.connIntvMax = CYBLE_GAPP_CONNECTION_INTERVAL_MAX;
                connUpdateParam.connLatency = CYBLE_GAPP_CONNECTION_SLAVE_LATENCY;
                connUpdateParam.supervisionTO = CYBLE_GAPP_CONNECTION_TIME_OUT;
                /* Request the parameter update */
                CyBle_L2capLeConnectionParamUpdateRequest(cyBle_connHandle.bdHandle, &connUpdateParam);
                DBG_PRINT("> Sending Param update request...\r\n");
            }
            break;
        }
        /* Device has been disconnected */
        case CYBLE_EVT_GAP_DEVICE_DISCONNECTED:{
            DBG_PRINT("> Disconnected from Central device\r\n");
            /* Start advertising again */
            startAdvertising();
            break;
        }
        /* Advertisement period complete */
        case CYBLE_EVT_GAPP_ADVERTISEMENT_START_STOP:{
            /* Check the state of the device */
            if(CyBle_GetState() == CYBLE_STATE_DISCONNECTED){
                DBG_PRINT("> Advertisement timeout \r\n");
                /* Restart advertisement */
                startAdvertising();
            }
            break;
        }
            
        /**********************************************************
        *                       GATT Events
        ***********************************************************/
        /* Device connected over GATT */
        case CYBLE_EVT_GATT_CONNECT_IND:{
            break;
        }
            
        /**********************************************************
        *                       Unknown Events
        ***********************************************************/
        default:
            break;
    }
}

/*******************************************************************************
* Function Name: startAdvertising()
********************************************************************************
*
* Summary:
*   Starts the Device advertising
*
* Parameters:
*   None
*
* Return:
*   advertisingResult - API result from the command
*
*******************************************************************************/
CYBLE_API_RESULT_T startAdvertising(void){
    /* Start advertising */
    CYBLE_API_RESULT_T advertisingResult = CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
    /* Print debugging info */
    if( advertisingResult == CYBLE_ERROR_OK){
        DBG_PRINT("> Starting advertisement\r\n");
    }
    else {
        DBG_PRINT("> StartAdvertisement API Error: ");
        DBG_PRINT_DEC_TEXT(advertisingResult, "\r\n");
    }
    return advertisingResult;
}
/* [] END OF FILE */