/***************************************************************************
*                                       MICA
* File: bleImu.c
* Workspace: IMU_v4.0
* Project Name: 01_IMU_App_v4.0
* Version: v4.0.0
* Author: Craig Cheney
* 
* PCB: MICA_IMU_v3.5.2
* PSoC: CYBLE-214015-01 (EZBLE, 4.2, 256k)
* Sensors: BOSCH IMU (BMX055)
* 
*
.

* Brief:
*   Code for controlling the BLE Stack for the MICA IMU
* 
* ChangeLog: 
* 2017.08.24 CC - Changed name to bleImu.c (from micaBle_imu.c),            ✓     
* 2017.08.13 CC - Added Program and BLE definitions, MVP                    ✓
* 2017.08.01 CC - Document created                                          ✓
* 
********************************************************************************/
#include "bleImu.h"
#include "powerManagement.h"

/* Static function prototypes */
static void bleCallback(uint32 event, void* eventParam);
static CYBLE_API_RESULT_T startAdvertising(void);
/* MICA Commands */
//static void processEnergyCommand(uint8 command, uint8* payload, uint16 length);
//static void processActuationCommand(uint8 command, uint8* payload, uint16 length);
//static void processPowerCommand(uint8 command, uint8* payload, uint16 length);
//static void processSensingCommand(uint8 command, uint8* payload, uint16 length);
//static void processCommunicationCommand(uint8 command, uint8* payload, uint16 length);
//static void processControlCommand(uint8 command, uint8* payload, uint16 length);



/*******************************************************************************
* Function Name: imuBle_init()
********************************************************************************
*
* Summary:
*   Initializes the BLE stack and hooks CyBle_ProcessEvents to the callback. 
*   Reads the local name from SFLASH, and loads. 
*
* Parameters:
*   None
*
* Return:
*   None
*
*******************************************************************************/
void imuBle_init(void){
    /* Start the BLE component */
    CyBle_Start(bleCallback);
    /* Read the local name from SFlash, and set that as the local name */
    char nameArray[Sflash_NAME_LEN];
    uint32 result = Sflash_ReadLocalName(nameArray);
    /* Ensure the read was successful */
    if(result == Sflash_ERR_OK) {
        /* Set the new local name */
        CyBle_GapSetLocalName(nameArray);   
    }
}



/*******************************************************************************
* Function Name: imuBle_processEvents()
********************************************************************************
*
* Summary:
*   Processes any BLE events on the stack 
*
* Parameters:
*   None
*
* Return:
*   None
*
*******************************************************************************/
void imuBle_processEvents(void){
    /* Process stack events - calls bleCallback() */
    CyBle_ProcessEvents(); 
    
}

/*******************************************************************************
* Function Name: imuBle_Callback()
********************************************************************************
*
* Summary:
*   Primary app call back for BLE. Processes the BLE stack events and acts
*   accordingly. 
*
* Parameters:
*   event - Event code generated by the stack
*   eventParam - pointer to the event parameters
*
* Return:
*   None
*
*******************************************************************************/
void bleCallback(uint32 event, void* eventParam) {
    /* Act according to event */
    switch(event){
        /**********************************************************
        *                       General Events
        ***********************************************************/
        /* Stack initialized; ready for advertisement */
        case CYBLE_EVT_STACK_ON:{
            /* Start advertising */
            startAdvertising();
            break;
        }
        /**********************************************************
        *                       GAP Events
        ***********************************************************/
        /* Device need to display passkey during secure connection pairing */
        case CYBLE_EVT_GAP_NUMERIC_COMPARISON_REQUEST:{
            /* Send the passkey for authentication */
            CyBle_GapAuthPassKeyReply(cyBle_connHandle.attId, PASSKEY_IGNORE, CYBLE_GAP_ACCEPT_PASSKEY_REQ);
            break;
        }
        /* Device has been connected - Indicate on LEDs and update connection parameters */
        case CYBLE_EVT_GAP_ENHANCE_CONN_COMPLETE:   /* When link layer privacy is enabled */
        case CYBLE_EVT_GAP_DEVICE_CONNECTED:{
            /* Update the LEDs */
            LEDS_Write(LEDS_ON_GREEN);
            /* Declare private variables used for connection update */
            CYBLE_GAP_CONN_UPDATE_PARAM_T connUpdateParam;
            CYBLE_GAP_CONN_PARAM_UPDATED_IN_CONTROLLER_T connParam;
            /* Cast event params */
            connParam = *(CYBLE_GAP_CONN_PARAM_UPDATED_IN_CONTROLLER_T*) eventParam;
            /* Ensure connection parameters are valid */
            if( connParam.connIntv > CYBLE_GAPP_CONNECTION_INTERVAL_MAX ){
                /* Configure requested params */
                connUpdateParam.connIntvMin = CYBLE_GAPP_CONNECTION_INTERVAL_MIN;
                connUpdateParam.connIntvMax = CYBLE_GAPP_CONNECTION_INTERVAL_MAX;
                connUpdateParam.connLatency = CYBLE_GAPP_CONNECTION_SLAVE_LATENCY;
                connUpdateParam.supervisionTO = CYBLE_GAPP_CONNECTION_TIME_OUT;
                /* Request the parameter update */
                CyBle_L2capLeConnectionParamUpdateRequest(cyBle_connHandle.bdHandle, &connUpdateParam);
            }
            /* Wakeup device */
            power_setSystemState(STATE_WAKEUP);
            break;
        }
        /* Device has been disconnected */
        case CYBLE_EVT_GAP_DEVICE_DISCONNECTED:{
            /* Start advertising again */
            startAdvertising();
            /* Set low power State */
            power_setSystemState(STATE_PREP_SLEEP);
            break;
        }
        /* Advertisement period complete */
        case CYBLE_EVT_GAPP_ADVERTISEMENT_START_STOP:{
            /* Check the state of the device */
            if(CyBle_GetState() == CYBLE_STATE_DISCONNECTED){
                /* Restart advertisement */
                startAdvertising();
            }
            break;
        } /* CYBLE_EVT_GAPP_ADVERTISEMENT_START_STOP */
            
               /**********************************************************
        *                       GATT Events
        ***********************************************************/
        /* MTU Exchange request - updates the negotiated MTU value */
        case CYBLE_EVT_GATTS_XCNHG_MTU_REQ:{
            /* Get the peer MTU in the event parameter */
            uint16 peerMtu = ((CYBLE_GATT_XCHG_MTU_PARAM_T *) eventParam)->mtu;
            /* Use the smaller of the two MTUs */
            uint16 negotiatedMtu = (peerMtu < CYBLE_GATT_MTU) ? peerMtu : CYBLE_GATT_MTU;   
            /* Store the MTU */
//            mica_setNegotiatedMtu(negotiatedMtu);
            /* Send the response */
            CyBle_GattsExchangeMtuRsp(cyBle_connHandle, negotiatedMtu);
            break;
        } /* CYBLE_EVT_GATTS_XCNHG_MTU_REQ */
        
        /* A write without response request was received */
        case CYBLE_EVT_GATTS_WRITE_CMD_REQ:{
//            micaLedToggle(MICA_LED_RED);
            LEDS_Write(LEDS_ON_RED);
            break;
        } /* CYBLE_EVT_GATTS_WRITE_CMD_REQ */
        
        /* Write request from the peer device */
        case CYBLE_EVT_GATTS_WRITE_REQ:{
            /* Cast write params */
            CYBLE_GATTS_WRITE_REQ_PARAM_T writeParam = *(CYBLE_GATTS_WRITE_REQ_PARAM_T*) eventParam;
            /* Respond to the write request */
            CyBle_GattsWriteRsp(cyBle_connHandle);
            break;
        }
        /**********************************************************
        *                       Unknown Events
        ***********************************************************/
        default:
            break;
    } /* event */
}

/*******************************************************************************
* Function Name: startAdvertising()
********************************************************************************
*
* Summary:
*   Starts the Device advertising
*
* Parameters:
*   None
*
* Return:
*   advertisingResult - API result from the command
*
*******************************************************************************/
CYBLE_API_RESULT_T startAdvertising(void){
    /* Start advertising */
    CYBLE_API_RESULT_T advertisingResult = CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
//    CYBLE_API_RESULT_T advertisingResult = CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_SLOW);
    /* Print debugging info */
    if( advertisingResult == CYBLE_ERROR_OK){
        /* Start successful */
    }
    else {
        /* If error occured */
    }
    return advertisingResult;
   
}

/* [] END OF FILE */